spring:
  datasource:
    url: jdbc:postgresql://ec2-44-207-60-135.compute-1.amazonaws.com:5432/d734tv3oe9ucn4
    username: rvodcncmzwfezd
    password: b6c933d1553e9410d5647f30d9b74510f61ee19423bbe4db334a860067bb1577
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
